### ISSUE TITLE
“createlang: command not found” 

### ISSUE THREAD

**Issue by Xiao-tuo** [CMASCenter/Speciation-Tool#1]
Hi, all
My PostgreSQL version is 13.
_createlang_ had been deprecated since PostgreSQL 9.1. 
Should I lower the pgSQL version？

#------

I install PostgreSQL 9.0.0 and it works 
and 
i test, but can't not found file 
_mechanism_description.7Feb2020.txt_ and _mechanism_forImport.11Feb2020.csv_
so,I make _ln -s_  follow:
mechanism_description.7Feb2020.txt -> sptool_mechanism_description_speciate5_0_04mar2020_v0.csv
mechanism_forImport.11Feb2020.csv -> mechanism_forImport_11Feb2020_speciate5_0_withSOAALK_13mar2020_v0.csv
Howerve, i run _init_sptooldb_v5.0.csh_ , it crushed,

parse() failed on argument: "RACM2_AE7", “Regional Atmospheric Chemistry Mechanism version 2 (RACM2) for CMAQ AERO7 aerosol scheme”, Y,"Ramboll Greg Yarwood provided mechanism per spreadsheet Mechanism_mappings_for_SPECIATE5_25June2020.xlsx on 29Jun2020","",""

_Parse failed at record 11
ERRORS:  Terminating import.  Correct the formatting problem and rerun.
ERROR: perl script failed for importing mechanism descriptions file /nwp/bx_xt/model/Speciation-Tool/import_data/mechanism_description.7Feb2020.txt_

Please help me. thanks!

BEST
xt

#---
ok ,i do it

**Comment by yshi-ramboll** [comment]
Hi Xiao-tuo,

Thank you for your feedback. We have updated the following files to address the issue you brought up:
  ./Assigns.sptool 
  ./import_data/sptool_mechanism_description_speciate5_0_04mar2020_v0.csv

Please let us know if you see other issues, thank you!
